version: 2.1
.directory: &directory
  working_directory: ~/repo
jobs:
  test:
  <<: *directory
  docker:
    - image: cimg/android:2023.08.1-node
    steps:
      - run:
          name: 'node version'
          command: 'node -v'
